name: ImpactMines
version: '1.0'
main: com.lucacando.impactMines.Main
api-version: '1.21'
authors: [ Luca Black ]
description: Mod for different QOL features used in survival minecraft.
website: https://lucacando.com
commands:
  reloadplayers:
    description: Loads all players.
  rank:
    description: Command to set player's ranks.
  gmc:
    description: Command to set player's gamemode to creative.
  gms:
    description: Command to set player's gamemode to survival.
  gmsp:
    description: Command to set player's gamemode to spectator.
  gma:
    description: Command to set player's gamemode to adventure.
  toolselect:
    description: Admin command to give tools.
    aliases:
      - toolselection
      - tools
  minewand:
    description: Gives player a mine wand to create a mine selection.
  fillmine:
    description: Fills a mine that's been selected by the player.
  removemine:
    description: Completely removes a mine from the world.